// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uthbafvvlzcqlxfnmlth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0aGJhZnZ2bHpjcWx4Zm5tbHRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MjA3NTcsImV4cCI6MjA1ODA5Njc1N30.-Tw3GrBKC1faqFUZsSwm-FudRsDyKbNhgD4jo3T-kxI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);